version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: monthly
    reviewers:
      - diginfra/engineering
    labels:
      - dependencies
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: monthly
    open-pull-requests-limit: 10
    reviewers:
      - diginfra/engineering
    labels:
      - dependencies
