name: Create PR assets

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build assets
    strategy:
      matrix:
        include:
          - target: windows
          - target: linux
          - target: darwin
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go 1.x
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Build project
        run: make ${{ matrix.target }}
      - name: Upload amd64 build artifact
        uses: actions/upload-artifact@v4
        if: ${{ matrix.target != 'windows' }}
        with:
          name: ${{ matrix.target }}-amd64
          path: "build/diginfra-${{ matrix.target }}-amd64"
      - name: Upload windows amd64 build artifact
        uses: actions/upload-artifact@v4
        if: ${{ matrix.target == 'windows' }}
        with:
          name: ${{ matrix.target }}-amd64
          path: "build/diginfra.exe"
      - name: Upload arm64 build artifact
        uses: actions/upload-artifact@v4
        if: ${{ matrix.target != 'windows' }}
        with:
          name: ${{ matrix.target }}-arm64
          path: "build/diginfra-${{ matrix.target }}-arm64"
      - name: Upload windows arm64 build artifact
        uses: actions/upload-artifact@v4
        if: ${{ matrix.target == 'windows' }}
        with:
          name: ${{ matrix.target }}-arm64
          path: "build/diginfra-arm64.exe"
