on:
  release:
    types: [published]
  workflow_dispatch:

name: Upload post-release assets

jobs:
  update-choco-version:
    if: ${{ !contains(github.ref, '-alpha') && !contains(github.ref, '-beta') }}
    name: Update Chocolatey version
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H 'authorization: Bearer ${{ secrets.POST_RELEASE_TRIGGERS_TOKEN }}' \
            https://api.github.com/repos/diginfra/chocolatey-packages/dispatches \
            -d '{"event_type":"diginfra_choco"}'

  update-atlantis-versions:
    if: ${{ !contains(github.ref, '-alpha') && !contains(github.ref, '-beta') }}
    name: Update Atlantis versions
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H 'authorization: Bearer ${{ secrets.POST_RELEASE_TRIGGERS_TOKEN }}' \
            https://api.github.com/repos/diginfra/diginfra-atlantis/dispatches \
            -d '{"event_type":"diginfra_atlantis"}'

  update-diginfra-docs:
    if: ${{ !contains(github.ref, '-alpha') && !contains(github.ref, '-beta') }}
    name: Update Diginfra Docs to reference latest CLI version
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H 'authorization: Bearer ${{ secrets.POST_RELEASE_TRIGGERS_TOKEN }}' \
            https://api.github.com/repos/diginfra/docs/dispatches \
            -d '{"event_type":"bump_cli_version"}'
